/*
************************************************************************
                            FIRST SOURCE
************************************************************************

SETUP ----> DOWNLOADING AND INSTALLING AN IDE(VS-CODE) AND C COMPILER

ADDING PATH TO ENVIRONMENT VARIABLE OF OS

SAMPLE CODE TO TEST THE SETUP

00.00.CHAPTER - 1 VARIABLES,DATATYPES AND OTHER BASIC
    00.01.HELLO WORLD PROGRAM ----> gcc filename.c (to compile), ./a.out (to extecute on linux or mac), ./a.exe(to execute on windows)
    00.02.VARIABLES AND RULES FOR NAMING THEM
    00.03.DATATYPES IN C
    00.04.CONSTANTS ----> INTEGER, REAL, CHARACTER
    00.05.KEYWORDS IN C(32)
    00.06.STRUCTURE OF A C PROGRAM
    00.07.COMMENTS
    00.08.FORMAT-SPECIFIRES
    00.09.INPUT-OUTPUT IN C
    00.10.PRACTICING TAKING INPUT FROM USER AND DISPLAYING OUTPUT IN C(SUM OF TWO INTEGERS)
    00.11.COMPILATION PROCESS
    00.12.PRACTICE PROBLEM - 1(AREA OF SQUARE)
    00.13.PRACTICE PROBLEM - 2(AREA OF CIRCLE)
    00.14.PRACTICE PROBLEM - 3(PERIMETER OF RECTANGLE)
    00.15.PRACTICE PROBLEM - 4(CUBE OF AN INTEGER)

01.00.CHAPTER - 2 INSTRUCTIONS AND OPERATORS
    01.01.INSTRUCTIONS AND ITS TYPES ----> TYPE DECLARATION, ARITHMETIC, CONTROL
    01.02.OPERATORS --->ARITHMETIC, RELATIONAL, LOGICAL, BITWISE, ASSIGNMENT, TERNARY
    01.03.PRACTICE PROBLEM ON OPERATORS - 1(DIVISIBILITY BY 2)
    01.04.PRACTICE PROBLEM ON OPERATORS - 2(IS_SUNDAY AND IS_SNOWING)
    01.05.PRACTICE PROBLEM ON OPERATORS - 3(IS_MONDAY OR IS_RAINING)
    01.06.PRACTICE PROBLEM ON OPERATORS - 4(IS A TWO DIGIT NUMBER)
    01.07.PRACTICE PROBLEM ON OPERATORS - 5(AVG OF 3 NUMBERS)
    01.08.PRACTICE PROBLEM ON OPERATORS - 6(CHECK IF ENTERED CHARACTER IS A DIGIT)
    01.09.PRACTICE PROBLEM ON OPERATORS - 7(SMALLEST OF THREE NUMBERS)

02.00 CHAPTER - 3 CONDITIONAL STATEMENTS
    02.01.USING IF-ELSE TO CHECK IF A PERSON IS AN ADULT OR NOT
    02.02.CODING THE PREVIOUS PROGRAM USING TERNARY OPERATOR
    02.03.USING SWITCH-CASE TO PRINT DAY NAME W.R.T DAY NUMBER
    02.04.USING IF-ELSE IF- ELSE TO DETERMINE IF A STUDENT IS PASS OR FAIL BASED ON MARKS OBTAINED
    02.05.MARKS BASED GRADING USING IF-ELSE LADDER
    02.06.CHECKING IF THE CHARACTER ENTERED IS LOWERCASE OR UPPERCASE

03.00 CHAPTER - 4 LOOPS
    03.01.INCREMENT AND DECREMENT OPERATORS



*/
